Add don't pack option to Manual Bake
absolute-quantum/cats-blender-plugin pull request #459
Opened 2022-05-13 17:16 UTC by 989onan

Maybe add a thing to not do this if decimating but keep it enabled if using normals because overlap is only a problem when normals and decimate are used together

2022-05-14 20:07 UTC, 989onan commented
first comment has now been resolved on the auto disable part

2022-06-13 04:34 UTC, feilen commented
I need to take a closer look, but would it be possible to add this as a different 'Generate UVMap' enum? I know it's not neccesarily correct in-name, but functionality wise it makes more sense to put it there.

If generate_uvmaps is getting too squished, you can remove 'expand=True' in ui/bake.py to turn it into a drop-down.

2022-07-06 19:39 UTC, feilen requested changes

2022-07-06 19:39 UTC, feilen commented on tools/bake.py
> +        pack_uvs = not (dont_pack_uvs and (not emit_indirect) and (not prioritize_face) and (not pass_ao) and (not any(plat.use_decimation for plat in context.scene.bake_platforms)))
This should just be "not dont_pack_uvs", if someone has explicitly selected "don't pack" then we should honor that, even if it'll have bad results.

2022-07-06 19:39 UTC, feilen commented on ui/bake.py
> +                    col.label(text="***Skipping the packing step will not work if one or more of your platforms has decimation active,***") #TRANSLATE PLEASE!
The emphasis is waaay overdone here. Just add a note that says:
"Warning: may have unexpected results if you have overlapping islands."

2022-07-06 19:40 UTC, feilen commented on ui/bake.py
> +                    col.label(text="***Skipping the packing step will not work if one or more of your platforms has decimation active,***") #TRANSLATE PLEASE!
otherwise looking great! I meant to add something like this forever ago

2023-03-01 20:23 UTC, 989onan commented
Fixed conflict with development branch so the codes are merged

2023-03-01 20:34 UTC, 989onan commented
sorry this is messy, but I'm using the website since it won't clone to my computer. The branch is so borked on my end. Maybe after the development merge it won't break so much. Github is complaining that some of the dependencies on my version before I pulled development into it didn't exist anymore and it was angy

2023-03-02 09:06 UTC, Darkblader24 commented
Thank you very much!

2023-03-02 09:06 UTC, merged